# fly.toml app configuration file generated for todool-backend on 2023-07-28T22:44:04-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "todool-backend"
primary_region = "sea"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"

[mounts]
  source="todooldata"
  destination="/data"
