version: "3"
services:
  backend:
    build:
      context: ./todos-api
      dockerfile: Dockerfile
    volumes:
      - ./todos-api:/app
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
